### ISSUE TITLE
Wahooo

### ISSUE THREAD

**Issue by ZmnSCPxj** [JeremyRubin/utxos.org#19]
I pledge my allegiance to the BIP 119, and for the `OP_CTV` for which it stands, one BIP under the BIP document editors, indivisible with utxos, covenants, and neat stuff for all.

Name ZmnSCPxj jxPCSnmZ
Supports Yes
Affiliations Randomly-generated Internet People

**Comment by JeremyRubin** [comment]
Amazing; thank you  ZmnSCPxj jxPCSnmZ may your entropy be blessed.
