### ISSUE TITLE
Support Indicated: No

### ISSUE THREAD

**Issue by BitcoinErrorLog** [JeremyRubin/utxos.org#28]
Generally, I do not think Bitcoin is ready for any new soft forked features at all in the short term. Taproot just arrived and there is already so much work to be done to adopt and utilize it.

Any improvements CTV-eltoo may bring to LN are not significant enough to claim they are urgent for adoption or R&D for LN progress and adoption.

As a non-engineer, yet more expert than the average Bitcoiner, I feel that covenants are not widely understood and I worry deeply that encumbering Bitcoin in such ways could have unforeseen consequences to the network, supply, and incentive structure. 

Since I am not qualified, nor are 99% of Bitcoiners, to evaluate this deeply, I feel much more time and scrutiny is required to accept CTV and the related projects Jeremy has prepared with it.

Furthermore, my position and lack of expertise, requires me to use trust signals to assess the situation, and Jeremy has been extremely aggressive in his promotion and persuasion to garner support for CTV, going so far as to frustrate Core devs during Taproot activation debates by trying to inject CTV into the conversation for consideration prematurely. This signaling tells me that, at best, his aggressive desire may even cause him to gloss over potential issues, and at worst, it tells me his incentives for including CTV may not have Bitcoiners' best interests at heart.

I am currently happy with what we have in Bitcoin, and would prefer Core development prioritize optimizations and cleanup work over more and more features that have no urgent need or chance of adoption anytime soon.

Therefore I cannot support CTV as a soft fork proposal in 2022, as a personal user, nor as CEO for Synonym.

**Comment by JeremyRubin** [comment]
did you want Synonym to be listed separately as a business or just you as individual?

**Comment by prayank23** [comment]
> I am currently happy with what we have in Bitcoin

I am not sure if this is true. Since Synonym wants to add features like tokens in LN, OP_CTV would help Synonym because users would be able to do more things with those tokens.

**Comment by BitcoinErrorLog** [comment]
> did you want Synonym to be listed separately as a business or just you as individual?

Both, please.

> > I am currently happy with what we have in Bitcoin
> 
> I am not sure if this is true. Since Synonym wants to add features like tokens in LN, OP_CTV would help Synonym because users would be able to do more things with those tokens.

Synonym is not proposing any changes to the Bitcoin protocol at this time. We are happy to explore fully utilizing Bitcoin as it already is, and believe there are still years worth of work to do to fully realize the potential of LN, taproot, etc.
