### ISSUE TITLE
Support Indicated: No

### ISSUE THREAD

**Issue by dmrobotix** [JeremyRubin/utxos.org#39]
We should never rush changes to Bitcoin.

**Comment by JeremyRubin** [comment]
Ok, I've gone ahead and added you as a "No".

----

That said, I can't help but strongly agree with you. We should never rush changes into Bitcoin. However, I (and many others) do not feel that BIP-119 is being rushed.

If you would like your NACK to carry more weight, your position would be greatly strengthened by writing up and sharing an analysis and commentary on exactly what parts of the process feel rushed to you. This should be 'satisfiable', i.e., what *could* an alternative effort do differently such that you would not feel it rushed? How has BIP-119 failed to meet this bar.

Best,

Jeremy
