### ISSUE TITLE
Support indicated: NO

### ISSUE THREAD

**Issue by andhan360** [JeremyRubin/utxos.org#44]

**Comment by JeremyRubin** [comment]
hi andi,

you should give a little more information on the reason for your no / who you are.

otherwise, this isn't clearly an account belonging to a real person since there's no history or links other than this no.

**Comment by andhan360** [comment]
Sure... I disagree that the research is sufficient in this field, even when your proposal is most matured and you are like "done so far before can moving on", but we can't be anyhow sure this would be the best proposal or way to go. Sad that you don't see potential here. I disagree we are well aware of the dangers too. We disagree on the urgency to have to choose and activate now. So far I can see some value but nothing what justifies imo to not try/work on other ways/proposals before activation. I oppose the speedy trial attempt. There is clear less support than you think and more disagreement than you show imo.

**Comment by JeremyRubin** [comment]
Ok -- is there any identity you'd like this linked to?

otherwise it is a reputationless comment, but I've gone ahead and added what you've written now.

**Comment by andhan360** [comment]
andhans or andhan360 is fine, others know, thanks.

**Comment by andhan360** [comment]
WHY ARE SOME NACKS NOT VISIBLE/ LISTED ON THE PAGE? 😂

**Comment by JeremyRubin** [comment]
Lemme look into it; I thought I committed a record for you...

**Comment by JeremyRubin** [comment]
Fixed -- the issue was, for some of the supporters/non supporters that the typo "Hightlight" got snuck in and copy-pasted... which prevented the rows from showing. I fixed this!
