### ISSUE TITLE
Support Indicated: No

### ISSUE THREAD

**Issue by Rspigler** [JeremyRubin/utxos.org#46]
I appreciate all the hard work you have put into Bitcoin (CTV and otherwise) - (I sponsor you and will continue to do so :) ).  So this is not personal but out of a desire to do what is best for Bitcoin.

You are not even close to gaining consensus on the proposal.  You are the only Core dev in support of the proposal (and you are the author, so that is a given).  Many devs have come out and spoken out against the proposal.  There has not been sufficient time to research all the alternatives proposed, and new ones continue to be discovered.  Once a new opcode is introduced, it must remain in Bitcoin's consensus forever, so this should not be a light decision we make.

I am very concerned that you have already proposed signalling.

I previously ACKed the proposal on your website, so would like to change my support to No.

Thank you.

**Comment by 1440000bytes** [comment]
> You are not even close to gaining consensus on the proposal. You are the only Core dev in support of the proposal (and you are the author, so that is a given). 

False. CTV has enough consensus, there are many core developers that reviewed CTV and okay with it.

**Comment by Rspigler** [comment]
Name 5 please

**Comment by 1440000bytes** [comment]
Developers that are Bitcoin Core contributors, reviewed CTV and okay with it (excluding activation method):

1. Luke Dashjr
2. James O'Beirne
3. benthecarman
4. Calvin Kim

Even I support CTV and new Bitcoin Core Contributor. My ACK will remain until I find any bugs in CTV that cannot be fixed or author refuses to fix them.

Since this is not just about Bitcoin Core but a soft fork for Bitcoin, there are other developers that support CTV and involved in other Bitcoin projects:

1. Lloyd Fournier
2. Olaoluwa Osuntokun
3. ZmnSCPxj

**Comment by earonesty** [comment]
imo: the main dev is super smart and this is moving way faster than most busy devs can follow.   just needs a bit more time.   i know it's frustrating when you're really invested, but open source needs consensus more than it needs "solutions today".

**Comment by Rspigler** [comment]
You can't exclude activation method. You listed 7 developers, there are hundreds total that should agree on this.  Do you think 7 people should have control over the protocol?

> open source needs consensus more than it needs "solutions today".

Absolutely

**Comment by JeremyRubin** [comment]
Clarification, do you prefer to be a NO on CTV in general, or a No on the independent activaiton proposal? Bear in mind the list is not being used to advance the specific activation parameters, and I can add a column to cover the activation proposals that are out there separately.

Currently, the page says:

> The following organizations, individuals, or pools have communicated preference for and intent to support a BIP-119 activation attempt using reasonable parameters. These “soft signals” are non-binding until an actual concrete proposal has been formed, but are useful for measuring community consensus. When a concrete proposal (e.g., parameters, binaries, etc) is launched, signatories on this list should not be considered to be supportive of that particular effort unless noted otherwise.

**Comment by Rspigler** [comment]
At the moment, NO for CTV in general. Until the alternatives are properly researched:

OP_CSFS, SH_APO, OP_CAT, OP_AMOUNT, OP_FOLD, OP_TXHASH, OP_EVICT, SIGHASH_BUNDLE, etc, and their interactions:

CAT+CSFS, CAT+CTV, CTV+CSFS, CTV+APO, etc

**Comment by JeremyRubin** [comment]
Ok, apologies for the delay in doing this just wanted to be clear on what the request is (& am doing a bunch of crap rn).

I'm figuring out the best way to update the table to provide accurate information and more context, I will let you know when it is done.

**Comment by Rspigler** [comment]
No problem, thanks

**Comment by JeremyRubin** [comment]
Ok -- let me know if it looks OK to you.

What I did was add a 'retraction' column and then have two entries for you, so people can see the evolution of thought process. As an alternative, I could drop the retraction link, and just have you link to your prior statement here? 

https://twitter.com/RobertSpigler/status/1453071438257131522

**Comment by JeremyRubin** [comment]
closing speculatively; reopen if unhappy...

**Comment by Rspigler** [comment]
I like the idea of having a retraction column with the date.  But it's a bit confusing IMO of have two column entries.  Maybe have the `date` entry hyperlink to my Github NO post, rather than creating a second column?  Up to you though of course.

As long as you have both posts I am good with it.  Thank you!

**Comment by JeremyRubin** [comment]
I agree it would be better if there were some way of e.g. grouping each one by person and showing the chain of events. I am not happy, but I don't have the time to make the perfect version of it sadly :(

If anyone you know has the interest in making this better, I'd be happy to review a patch.

The reason I did the date thing rather than link is to let you retract the retraction in the future, if your contingencies clear.

**Comment by Rspigler** [comment]
:+1:
